model = "gpt-5.5"
model_reasoning_effort = "xhigh"
notify = ["/Users/edte/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]
service_tier = "default"

[projects."/Users/edte/go/src/push/push-manage-console"]
trust_level = "trusted"

[projects."/Users/edte/.local/share/nvim/lazy/git-messenger.vim"]
trust_level = "trusted"

[projects."/Users/edte/.local/share/nvim/lazy/git-blame.nvim"]
trust_level = "trusted"

[projects."/Users/edte/.local/share/nvim/lazy"]
trust_level = "trusted"

[projects."/Users/edte/.local/share/nvim/lazy/foldtext.nvim"]
trust_level = "trusted"

[projects."/Users/edte/dotfiles"]
trust_level = "trusted"

[projects."/Users/edte"]
trust_level = "untrusted"

[projects."/Users/edte/.local/share/nvim/lazy/wilder.nvim"]
trust_level = "trusted"

[projects."/Users/edte/.local/share/nvim/lazy/codecompanion.nvim"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/push-dispatch-service"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/record/push-record-service"]
trust_level = "trusted"

[projects."/Users/edte/go/src/test/claudekit-skills"]
trust_level = "trusted"

[projects."/Users/edte/.local/share/nvim/lazy/namu.nvim"]
trust_level = "trusted"

[projects."/Users/edte/go/src/wns_project/jce"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/push-nodisturbe-service"]
trust_level = "trusted"

[projects."/Users/edte/Desktop"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/dashboard/push-dashboard-sync"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/push-huawei-recommend"]
trust_level = "trusted"

[projects."/Users/edte/go/src/wns_project"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/flow/push-feedback"]
trust_level = "trusted"

[projects."/Users/edte/code/jce-lsp"]
trust_level = "trusted"

[projects."/Users/edte/.local/share/nvim/lazy/codelens.nvim"]
trust_level = "trusted"

[projects."/Users/edte/go/src/test"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/push-action-service"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/push-plugin-service"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/push-engine-service"]
trust_level = "trusted"

[projects."/Users/edte/Desktop/workspace"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/ratelimit/push-ratelimit-service"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/device/push-device"]
trust_level = "trusted"

[projects."/Users/edte/go/src/wns_project/jce/push"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/push-gateway"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/logic/push-logic"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/offline/push-apns"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/push-dynamic-island-dispatch"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/push-dynamic-island-gateway"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/push-island-device"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/tpush/tpush-server"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/device/push-online"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/offline/push-harmony"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/bill/push-bill-consumer"]
trust_level = "trusted"

[projects."/Users/edte/.codex"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/offline/push-and"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/push-cmd-service"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/push-resource-proxy"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/push-template-service"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/push-strategy-service"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/bill/push-bill-producer"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/flow/push-monitor"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/push-island-gateway"]
trust_level = "trusted"

[projects."/Users/edte/go/src/push/common"]
trust_level = "trusted"

[[skills.config]]
path = "/Users/edte/.codex/skills/.system/skill-creator/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/edte/.codex/skills/.system/skill-installer/SKILL.md"
enabled = false

# [mcp_servers.sequential-thinking]
# command = "npx"
# args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]

# [mcp_servers.neovim]
# command = "npx"
# args = ["-y", "mcp-neovim-server"]
#
# [mcp_servers.neovim.env]
# NVIM_MCP_LISTEN_ADDRESS = "/tmp/nvim"
# ALLOW_SHELL_COMMANDS = "true"

[notice]
hide_rate_limit_model_nudge = true

[tui]
status_line = ["model-with-reasoning", "current-dir"]
status_line_use_colors = true


[tui.model_availability_nux]
"gpt-5.5" = 4

[hooks.state]

[hooks.state."/Users/edte/.codex/hooks.json:pre_tool_use:0:0"]
trusted_hash = "sha256:fc87dbee1cb8a9be4f78ba094c4fa8d5e2fd38cb800854e3717f9b6a52fe2a47"

[hooks.state."/Users/edte/.codex/hooks.json:post_tool_use:0:0"]
trusted_hash = "sha256:ac371f260e4b23ba1d1b7a4ad68a44a323a8470b61f38471a47aceac1b7a5a7c"

[marketplaces.openai-bundled]
last_updated = "2026-06-17T12:34:11Z"
source_type = "local"
source = "/Users/edte/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.claude-plugins-official]
last_updated = "2026-07-01T01:55:25Z"
last_revision = "317b8988055b151b694d4e06e5039b3f38dbe425"
source_type = "git"
source = "https://github.com/anthropics/claude-plugins-official.git"

[marketplaces.openai-primary-runtime]
last_updated = "2026-06-17T13:22:56Z"
source_type = "local"
source = "/Users/edte/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[features]
js_repl = false

[mcp_servers.node_repl]
args = []
command = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/Codex.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/edte/.codex"
CODEX_HOME = "/Users/edte/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "099cb5ac09333da8389063d49d03a7e277fc87d858b0526a538f0871af93bf68"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.611.61753"
CODEX_CLI_PATH = "/Applications/Codex.app/Contents/Resources/codex"

[desktop.open-in-target-preferences]
global = "terminal"

[desktop.open-in-target-preferences.perPath]
"/Users/edte/go/src/push/push-strategy-service" = "terminal"
