all:
	mv ~/.codebuddy/CODEBUDDY.md ~/.codebuddy/CODEBUDDY.md.bk
	ln -s ~/dotfiles/claude/CODEBUDDY.md  ~/.codebuddy/CODEBUDDY.md

	mv ~/.codebuddy.json ~/.codebuddy.json.bk
	ln -s ~/dotfiles/claude/mcp.json  ~/.codebuddy.json

	mv ~/.codebuddy/settings.json ~/.codebuddy/settings.json.bk
	ln -s ~/dotfiles/claude/settings.json  ~/.codebuddy/settings.json

	mv ~/.codebuddy/.lsp.json ~/.codebuddy/.lsp.json.bk
	ln -s ~/dotfiles/claude/lsp.json  ~/.codebuddy/.lsp.json

